.PHONY: clean All

All:
	@echo "----------Building project:[ hello - Debug ]----------"
	@$(MAKE) -f  "hello.mk"
clean:
	@echo "----------Cleaning project:[ hello - Debug ]----------"
	@$(MAKE) -f  "hello.mk" clean
